name: flutter app build 🚀🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "pawsome_client/**"

env:
  FLUTTER_VERSION: "3.10.3"
  FLUTTER_CHANNEL: "stable"

jobs:
  build_android:
    name: Android APK Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pawsome_client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "${{env.FLUTTER_VERSION}}"
          channel: "${{env.FLUTTER_CHANNEL}}"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: pawsome_client/build/app/outputs/flutter-apk/app-release.apk
